package cm.klg.notification.domaine.notification;

public enum NotificationType {
  SERVICE_REQUEST_CREATED,
  SERVICE_REQUEST_ACCEPTED,
  SERVICE_REQUEST_REJECTED,
  SERVICE_REQUEST_CANCELLED,
  SERVICE_PROVIDER_CREATED,
  SERVICE_PROVIDER_APPROVED,
  SERVICE_PROVIDER_REJECTED
}
